#ifndef PdfIOMan_h
#define PdfIOMan_h

#include <TCanvas.h>
#include <TPaveText.h>
#include <TSystem.h>
#include <TDatime.h>
#include <TMD5.h>
#include <TROOT.h>
#include <TString.h>
#include <TStyle.h>
#include <TObjArray.h>
#include <TObjString.h>
#include <vector>
#include <string>
#include <cstring>
#include <iostream>

namespace PdfHeader {

  // --- Internal Helper Functions ---

  inline TString _Md5ToHex(const char* s) {
    return (s && s[0]) ? TString(s) : TString("");
  }

  // Rename local variable 'hex' to 'sHex' to avoid CINT collision
  inline TString _Md5ToHex(TMD5* p) {
    if (!p) return TString("");
    TString sHex = p->AsString(); 
    delete p;
    return sHex;
  }

  inline TString ComputeMD5Hex(const char* fn) {
    if (gSystem->AccessPathName(fn)) return "not found";
  
    TMD5* res = TMD5::FileChecksum(fn); 
    // Rename local variable 'hex' to 'md5Res' to avoid CINT collision
    TString md5Res = _Md5ToHex(res);
  
    if (md5Res.IsNull()) {
      TString alt = gSystem->GetFromPipe(Form("md5sum '%s' 2>/dev/null | awk '{print $1}'", fn));
      alt = alt.Strip(TString::kBoth, '\n');
      if (!alt.IsNull()) md5Res = alt;
    }
    return md5Res.IsNull() ? TString("N/A") : md5Res;
  }  

  // --- Public Functions ---

  inline void OpenPdf(TString outpdf){
    TCanvas* copn = new TCanvas("copn", "__pdf_open__", 100, 100);        
    copn->Print(outpdf + "["); 
    delete copn;
  }

  inline void ClosePdf(TString outpdf){  
    TCanvas* ccls = new TCanvas("ccls", "__pdf_close__", 100, 100);    
    ccls->Print(outpdf + "]"); 
    delete ccls;
  }
  
  inline void MakePdfHeaderPage(TString outpdf,
				const char* macroName,
				const std::vector<std::string>& inputFiles,      
				const char* extraNote = "",
				bool landscape = true,
				const char* anaName = 0)
  {
    if (landscape) gStyle->SetPaperSize(29.7, 21.0);
    else           gStyle->SetPaperSize(21.0, 29.7);
  
    const char* user  = gSystem->Getenv("USER");
    TString host      = gSystem->HostName();
    TString cwd       = gSystem->WorkingDirectory();
    TString rootver   = gROOT->GetVersion();
    TDatime now;
    TString nowSQL = now.AsSQLString();

    TString gitHash;
    TString pipe = gSystem->GetFromPipe("git rev-parse --short HEAD 2>/dev/null");
    pipe = pipe.Strip(TString::kBoth, '\n');
    if (!pipe.IsNull()) gitHash = pipe;
    else gitHash = "(no git)";

    const int W = landscape ? 1200 : 900;
    const int H = landscape ?  800 : 1270;

    TCanvas *chd = new TCanvas("c_header","Run Info", W, H);
    chd->SetFillColor(0);
    chd->SetMargin(0.08, 0.06, 0.10, 0.08);
  
    TPaveText *title = new TPaveText(0.08, 0.86, 0.94, 0.96, "NDC");
    title->SetFillColor(0); title->SetBorderSize(0);
    title->SetTextFont(62); title->SetTextSize(0.05);
    title->AddText("Analysis Report - QA Check");
    title->Draw();

    TPaveText *body = new TPaveText(0.08, 0.12, 0.94, 0.83, "NDC");
    body->SetFillColor(0); body->SetBorderSize(1);
    body->SetTextFont(42); body->SetTextSize(0.032);
    body->SetTextAlign(12);

    body->AddText(Form("Created at : %s", nowSQL.Data()));
    body->AddText(Form("User/Host  : %s @ %s", (user?user:"(unknown)"), host.Data()));
    body->AddText(Form("Work dir   : %s", cwd.Data()));
    body->AddText(Form("ROOT ver.  : %s", rootver.Data()));
    body->AddText(Form("Macro      : %s", macroName));
    if (anaName && anaName[0] != '\0') {
      body->AddText(Form("Analysis (conf) : %s", anaName));
    }
    body->AddText(Form("Git commit : %s", gitHash.Data()));
    body->AddText(" ");
    body->AddText("Input files:");
    for (size_t i=0;i<inputFiles.size();++i){
      const char* fn = inputFiles[i].c_str();
      TString fileMd5 = ComputeMD5Hex(fn);
      TString filenameOnly = gSystem->BaseName(fn);
      body->AddText(Form("  [%lu] %s (MD5: %s)", (unsigned long)i, filenameOnly.Data(), fileMd5.Data()));
    }  
    if (extraNote && std::strlen(extraNote)>0){
      body->AddText(" "); 
      body->AddText("Configuration / Notes:");
      TString noteStr(extraNote);
      TObjArray* lines = noteStr.Tokenize("\n");
      for(int il=0; il<lines->GetEntries(); il++){
	body->AddText(Form("  %s", ((TObjString*)lines->At(il))->GetString().Data()));
      }
      delete lines;
    }
    body->Draw();

    TPaveText *foot = new TPaveText(0.08, 0.04, 0.94, 0.10, "NDC");
    foot->SetFillColor(0); foot->SetBorderSize(0);
    foot->SetTextFont(42); foot->SetTextSize(0.02);
    foot->AddText("Generated by PdfIOMan.h");
    foot->Draw();

    chd->Update();
    chd->Print(outpdf);

    delete title;
    delete body;
    delete foot;
    delete chd;
  }

} // namespace PdfHeader
#endif
